name: JJ MILLEN
favicon: null
layout_spectrum: 0.5329423029907048
typography_spectrum: 0.8892135582864285
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efefef'
    - '#214c6f'
    - '#aaaaaa'
    - '#cccccc'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
